//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int cId { get; set; }
        public string cBody { get; set; }
        public int pId { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual post post { get; set; }
        public virtual user user { get; set; }
    }
}
